name: Terpconnect Clone

on:
  workflow_dispatch:


jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    
    steps:
      # Copies all files to terpconnect
      - name: Login and Clone Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ..
            cd pub
            ssh-keyscan -H github.com >> /afs/glue.umd.edu/home/glue/j/r/jrobin13/home/.ssh/known_hosts
            git clone git@github.com:justinrobinson1020/justinrobinson1020.github.io.git
